import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import HeroCarousel from '../../components/HeroCarousel';
import NewArrivals from '../../components/NewArrivals';
import BestSelling from '../../components/BestSelling';
import UploadPrescriptionSection from '../../components/UploadPrescriptionSection';
import BlogCard from '../../components/blog/BlogCard';

export default function HomePage() {
  const navigate = useNavigate();
  const [blogPosts, setBlogPosts] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchBlogs = async () => {
      try {
        const response = await fetch(`http://localhost:5000/api/customer/blogs/latest`);
        if (!response.ok) throw new Error(`Server error: ${response.status}`);
        const data = await response.json();
        setBlogPosts(Array.isArray(data) ? data : []);
      } catch (error) {
        console.error("Error fetching blogs:", error.message);
        setBlogPosts([]);
      } finally {
        setLoading(false);
      }
    };
    fetchBlogs();
  }, []);

  return (
    <div className="bg-white w-full">

      {/* HERO */}
      <HeroCarousel />

      {/* NEW ARRIVALS */}
      <NewArrivals />

      {/* UPLOAD SECTION */}
      <UploadPrescriptionSection onOpen={() => navigate("/customer/prescription")} />

      {/* BEST SELLING */}
      <BestSelling />

      {/* AI Generated Blogs Section - WHO Guidelines Compliant */}
      <section className="py-16 container mx-auto px-4 bg-gray-50 mt-10 rounded-t-3xl">
        <h2 className="text-3xl font-bold text-center mb-12 text-gray-800" style={{ fontFamily: "'Raleway', sans-serif" }}>
          Latest Health Insights
        </h2>
        
        {loading ? (
          <div className="flex justify-center items-center py-20">
            <p className="text-gray-500 animate-pulse text-lg">Fetching the latest insights...</p>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-10">
            {blogPosts.length > 0 ? (
              blogPosts.slice(0, 3).map((blog, index) => (
                <BlogCard 
                  key={`${blog.id}-${index}`}
                  id={blog.id}
                  title={blog.title ? blog.title.replace(/\*\*/g, '') : "MediCareX Health Tip"}
                  imageUrl={blog.imageUrl}
                  excerpt={blog.content} 
                />
              ))
            ) : (
              <div className="col-span-3 text-center py-20 bg-white rounded-3xl border border-dashed border-gray-200">
                <p className="text-gray-400 italic">No health insights found at the moment. Please check back later.</p>
              </div>
            )}
          </div>
        )}

        {/* Mandatory Medical Disclaimer */}
        <div className="mt-16 text-center text-[10px] text-gray-400 italic p-6 bg-white rounded-2xl border border-gray-100 max-w-4xl mx-auto shadow-sm">
          <p className="leading-relaxed">
            Disclaimer: This information is generated by AI based on public health guidelines and is for educational purposes only. 
            It is not a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of 
            your physician or other qualified health provider with any questions you may have regarding a medical condition.
          </p>
        </div>
      </section>

    </div>
  );
}