import { useState } from 'react';
import Card from '../../components/Card';
import { useNotifications } from '../../components/admin/useNotifications';
import { FilterBar } from '../../components/admin/FilterBar';
import { NotificationCard } from '../../components/admin/NotificationCard';
import { NotificationModal } from '../../components/admin/NotificationModal';

/**
 * EmptyState — reusable placeholder shown when the notification list is empty
 * or still loading. Accepts an optional subtitle for additional context.
 *
 * @param {string} message - Primary message displayed in the centre of the card.
 * @param {string} [sub]   - Optional secondary line shown in smaller text below.
 */
const EmptyState = ({ message, sub }) => (
  <div className="bg-white rounded-xl shadow-sm py-20 text-center text-slate-500">
    <p className="text-lg mb-2">{message}</p>
    {sub && <small className="text-sm text-slate-400">{sub}</small>}
  </div>
);

/**
 * Notifications page — central hub for admin notifications generated by supplier
 * actions (order approvals, rejections) and system events (low stock alerts).
 *
 * Responsibilities:
 *   - Consumes the useNotifications hook which owns all Firestore reads and writes.
 *   - Provides a type-based filter so the admin can focus on a specific category.
 *   - Displays summary stat cards for quick counts by notification type.
 *   - Opens a detail modal when the admin selects a notification, allowing them
 *     to mark it as read, mark it as received, or delete it.
 */
const Notifications = () => {
  const { notifications, loading, markAsRead, markAllAsRead, deleteById, markReceived } = useNotifications();

  const [filter, setFilter]   = useState('All');    // active type filter; "All" shows every notification
  const [selected, setSelected] = useState(null);   // notification currently open in the detail modal

  // Apply the active type filter; "All" bypasses filtering entirely
  const filtered = filter === 'All' ? notifications : notifications.filter((n) => n.type === filter);

  // Derived count used in the stat card and the "Mark All as Read" button label
  const unreadCount = notifications.filter((n) => !n.read).length;

  /**
   * Configuration array for the four summary stat cards.
   * Each entry is derived from the full (unfiltered) notifications array so the
   * counts remain consistent regardless of the active filter tab.
   */
  const statCards = [
    { title: 'Total Notifications', value: notifications.length },
    { title: 'Unread',              value: unreadCount },
    { title: 'Orders Approved',     value: notifications.filter((n) => n.type === 'ORDER_APPROVED').length },
    { title: 'Low Stock Alerts',    value: notifications.filter((n) => n.type === 'LOW_STOCK_ALERT').length },
  ];

  return (
    <div className="p-8 bg-slate-50 min-h-screen">

      {/* Page Header — "Mark All as Read" button only shown when unread notifications exist */}
      <div className="flex justify-between items-start mb-7 flex-wrap gap-4">
        <div>
          <h1 className="text-3xl font-bold text-slate-800 mb-2">Notifications</h1>
          <p className="text-slate-500 text-[15px]">Stay updated with supplier responses and stock alerts</p>
        </div>
        {unreadCount > 0 && (
          <button
            onClick={markAllAsRead}
            className="px-5 py-3 bg-blue-600 hover:bg-blue-700 text-white text-sm font-semibold rounded-lg border-none cursor-pointer transition-all hover:-translate-y-0.5 hover:shadow-md"
          >
            Mark All as Read ({unreadCount})
          </button>
        )}
      </div>

      {/* Summary Stat Cards — counts across all notifications, unaffected by the active filter */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-5 mb-7">
        {statCards.map((card) => <Card key={card.title} {...card} />)}
      </div>

      {/* Filter Bar — allows the admin to narrow the list by notification type */}
      <FilterBar filter={filter} onFilter={setFilter} />

      {/* Notification List — three render states: loading, empty, and populated */}
      <div className="flex flex-col gap-4">
        {loading ? (
          // Loading state — shown while useNotifications fetches from Firestore
          <EmptyState message="Loading notifications..." />
        ) : !filtered.length ? (
          // Empty state — shown when the active filter returns no results
          <EmptyState message="No notifications found" sub="You'll see updates from suppliers here" />
        ) : (
          // Populated state — each notification rendered as a card; clicking opens the detail modal
          filtered.map((n) => (
            <NotificationCard
              key={n.id}
              notification={n}
              onClick={setSelected}
              onMarkRead={markAsRead}
            />
          ))
        )}
      </div>

      {/* Detail Modal — rendered only when a notification is selected; null closes it */}
      {selected && (
        <NotificationModal
          notification={selected}
          onClose={() => setSelected(null)}
          onMarkRead={markAsRead}
          onDelete={deleteById}
          onMarkReceived={markReceived}
        />
      )}

      {/* Keyframe animations used by modal and card entrance transitions */}
      <style>{`
        @keyframes fadeIn  { from { opacity: 0 }              to { opacity: 1 } }
        @keyframes slideUp { from { transform: translateY(30px); opacity: 0 } to { transform: translateY(0); opacity: 1 } }
      `}</style>
    </div>
  );
};

export default Notifications;